- block:
  - name: create destination directory
    ansible.builtin.file:
      state: directory
      mode: 0755
      path: "{{ software_dir }}"
      
  - name: download waveshare ups hat software
    ansible.builtin.get_url:
      url: https://files.waveshare.com/wiki/UPS-HAT-D/UPS_HAT_D.7z
      dest: "{{ software_dir }}"
    register: r_download_ups
  
  - name: extract sofware
    ansible.builtin.shell: "/usr/bin/7zr x {{ r_download_ups.dest }} -r -o{{ software_dir }}"
    when: r_download_ups.changed

  - name: enable battery tray
    ansible.builtin.shell: 
      cmd: "./main.sh"
      chdir: "{{ software_dir }}/UPS_HAT_D/"

  - name: manual action in GUI
    ansible.builtin.debug:
      msg: |
        install ans configure signalk-raspberry-pi-ina219 plugin
        Appstore > signalk-raspberry-pi-ina219 plugin > install
        Server > Plugin configure > Rspberry-Pi ina219
          SignalK Path of voltage: electrical.batteries.plotter.voltage
          Also send the current data to SignalK: true
          SignalK Path of current: electrical.batteries.plotter.current
          I2C bus number: 1
          I2C address: 0x43
  # become: true
  # become_user: root